CREATE TABLE "ANIMALS" (
	ANIMAL_ID BIGINT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	HUNGER INT DEFAULT 0,
	ENERGY INT DEFAULT 5,
	AGE INT DEFAULT 0,
	IS_DEAD BOOLEAN DEFAULT FALSE,
	PRIMARY KEY (ANIMAL_ID)
);

CREATE SEQUENCE "ANIMALS_SEQ"
	MINVALUE 2000 MAXVALUE 999999999 INCREMENT BY 1
    START WITH 2000 NOCACHE NOCYCLE;