CREATE TABLE "ZOO" (
    ZOO_ID BIGINT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255) NOT NULL,
    CURRENT_DAY INT DEFAULT 0,
    PRIMARY KEY (ZOO_ID)
);

CREATE SEQUENCE "ZOO_SEQ"
    MINVALUE 2000 MAXVALUE 999999999 INCREMENT BY 1
    START WITH 2000 NOCACHE NOCACHE;

CREATE TABLE "ANIMALS" (
	ANIMAL_ID BIGINT NOT NULL AUTO_INCREMENT,
	ZOO_ID BIGINT NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	HUNGER INT DEFAULT 0,
	ENERGY INT DEFAULT 5,
	AGE INT DEFAULT 0,
	IS_DEAD BOOLEAN DEFAULT FALSE,
	BIRTH_DAY INT DEFAULT 0,
	PRIMARY KEY (ANIMAL_ID),
	FOREIGN KEY(ZOO_ID) REFERENCES ZOO(ZOO_ID)
);

CREATE SEQUENCE "ANIMALS_SEQ"
	MINVALUE 2000 MAXVALUE 999999999 INCREMENT BY 1
    START WITH 2000 NOCACHE NOCYCLE;

